In [1]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.random.rand()

0.29561991638437

In [32]:
np.random.rand(4)

array([0.73440181, 0.61091961, 0.22500178, 0.98394168])

In [33]:
np.random.rand(4,4)

array([[0.45648633, 0.37470342, 0.58284563, 0.91659279],
       [0.51826856, 0.82356291, 0.75171378, 0.78765858],
       [0.2495377 , 0.30317781, 0.6355648 , 0.97904556],
       [0.99555252, 0.48515455, 0.01228987, 0.65788183]])

In [34]:
np.random.randint(1,15)

3

In [35]:
np.random.randint(1,100,(10,10))

array([[16, 54, 15, 65, 44, 17, 62,  3,  9, 60],
       [93, 77, 46, 80, 13, 64,  8, 40, 68, 53],
       [33, 68, 78, 49, 78, 14, 78, 39,  8, 20],
       [95, 44, 37, 17, 64,  1,  9, 70, 51, 64],
       [22, 62, 28, 39, 42, 45, 51, 77, 14, 87],
       [29, 51, 37, 92, 43, 67,  4, 12, 65, 90],
       [98, 73, 96, 84, 54, 24, 92, 20, 82, 32],
       [59, 24, 12, 15, 87, 39,  6, 14, 12, 76],
       [16, 46,  9, 37, 77, 54,  4, 33, 45, 14],
       [60, 89, 81, 93, 46, 63, 59, 97, 59, 36]])