In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,20,10)

In [3]:
matriz=arr.reshape(2,5)
matriz

array([[17,  1,  6,  8, 16],
       [16, 10,  5, 19,  5]])

In [4]:
arr.max()

19

In [5]:
matriz

array([[17,  1,  6,  8, 16],
       [16, 10,  5, 19,  5]])

In [8]:
matriz.max(0)

array([17, 10,  6, 19, 16])

In [11]:
arr.argmax()

8

In [13]:
matriz.argmax(0)

array([0, 1, 0, 1, 0], dtype=int64)

In [15]:
matriz.min()

1

In [16]:
arr

array([17,  1,  6,  8, 16, 16, 10,  5, 19,  5])

In [17]:
arr.ptp()

18

In [21]:
matriz.ptp(0)

array([ 1,  9,  1, 11, 11])

In [24]:
np.percentile(arr,50)

9.0

In [25]:
arr.sort()

In [26]:
arr

array([ 1,  5,  5,  6,  8, 10, 16, 16, 17, 19])

In [27]:
np.median(arr)

9.0

In [30]:
np.median(matriz,1)

array([ 5., 16.])

In [33]:
np.std(arr)**2

35.21

In [32]:
np.var(arr)

35.21

In [34]:
np.mean(arr)

10.3

In [52]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [53]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [54]:
a.ndim

2

In [55]:
b.ndim

1

In [56]:
b=np.expand_dims(b,axis=0)

In [57]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
b.shape

(1, 2)