In [1]:
import numpy as np

In [2]:
lista=[1,2]
lista

[1, 2]

In [3]:
lista * 2

[1, 2, 1, 2]

In [4]:
arr = np.arange(0,10)
arr2 = arr.copy()

### Operaciones

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
1/arr

C:\Users\Pedro\AppData\Local\Temp\ipykernel_15068\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr *arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [13]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [16]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [18]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])