In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr

array([[3, 4],
       [8, 1],
       [9, 8]])

In [6]:
arr.reshape(1,6)

array([[3, 4, 8, 1, 9, 8]])

In [7]:
arr.reshape(2,3)

array([[3, 4, 8],
       [1, 9, 8]])

In [8]:
np.reshape(arr,(1,6))

array([[3, 4, 8, 1, 9, 8]])

In [9]:
arr

array([[3, 4],
       [8, 1],
       [9, 8]])

In [10]:
np.reshape(arr,(2,3),'C')


array([[3, 4, 8],
       [1, 9, 8]])

In [11]:
np.reshape(arr,(2,3),'F')

array([[3, 9, 1],
       [8, 4, 8]])

In [12]:
np.reshape(arr,(2,3),'A')

array([[3, 4, 8],
       [1, 9, 8]])